-- MySQL Script generated by MySQL Workbench
-- Tue Feb 20 17:37:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SemImagesDatabase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SemImagesDatabase` ;

-- -----------------------------------------------------
-- Schema SemImagesDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SemImagesDatabase` DEFAULT CHARACTER SET utf8 ;
USE `SemImagesDatabase` ;

-- -----------------------------------------------------
-- Table `SemImagesDatabase`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SemImagesDatabase`.`images` ;

CREATE TABLE IF NOT EXISTS `SemImagesDatabase`.`images` (
    `image_id` INT NOT NULL AUTO_INCREMENT,
    `image` LONGBLOB NOT NULL,
    `beam_kv` INT NOT NULL,
    `magnification` INT NOT NULL,
    `working_depth` INT NOT NULL,
    `up_votes` INT NOT NULL DEFAULT 0,
    `colored` TINYINT NOT NULL,
    `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `session_id` INT NOT NULL DEFAULT 0,
    UNIQUE INDEX `image_id_UNIQUE` (`image_id` ASC),
    PRIMARY KEY (`image_id`)
)  ENGINE=INNODB;


-- -----------------------------------------------------
-- Table `SemImagesDatabase`.`sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SemImagesDatabase`.`sessions` ;

CREATE TABLE IF NOT EXISTS `SemImagesDatabase`.`sessions` (
    `session_id` INT NOT NULL AUTO_INCREMENT,
    `timestamp` TIMESTAMP NOT NULL,
    PRIMARY KEY (`session_id`),
    UNIQUE INDEX `session_id_UNIQUE` (`session_id` ASC)
)  ENGINE=INNODB;


CREATE TABLE IF NOT EXISTS `SemImagesDatabase`.`operators` (
    `operator_id` INT NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(45) NULL DEFAULT NULL,
    `last_name` VARCHAR(45) NULL DEFAULT NULL,
    `initials` VARCHAR(45) NULL DEFAULT NULL,
    PRIMARY KEY (`operator_id`),
    UNIQUE INDEX `operator_id_UNIQUE` (`operator_id` ASC)
)  ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS `SemImagesDatabase`.`sessions_operators` (
    `session_id` INT NOT NULL,
    `operator_id` INT NOT NULL,
    FOREIGN KEY (`session_id`)
        REFERENCES `sessions` (`session_id`),
    FOREIGN KEY (`operator_id`)
        REFERENCES `operators` (`operator_id`)
)  ENGINE=INNODB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
